### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by jacobbogdanov** [esimonov/ifshort#6]
the following code
```go
package main

import (
	"context"
	"fmt"
)

func main() {

	ctx := context.Background()
	value := ctx.Value("key")
	if value == nil {
		panic("")
	}

	fmt.Println(value.(string))
}

```
produces this error (when running through `golangci-lint` version 1.36.0);
```
test.go:11:2: variable 'value' is only used in the if-statement (test.go:12:2); consider using short syntax (ifshort)
        value := ctx.Value("key")
```

**Comment by AlekSi** [comment]
I have a similar case:
 ```go
ch := c.responses[id]
if ch == nil {
	c.m.Unlock()
	c.close(errors.WithStack(fmt.Errorf("no subscriber for ID %d", id)))
	return
}

delete(c.responses, id)
c.m.Unlock()
ch <- resp
 ```

**Comment by jacobbogdanov** [comment]
and I think I found another one;
```go
package main

import "fmt"

func main() {
	name := "Jacob"

	_ = "random data" + name // <- this usage is not being seen

	if false {
		fmt.Printf("my name is %s", name)
	}
}
```
produces this error (when running through `golangci-lint` version 1.36.0);
```
main.go:6:2: variable 'name' is only used in the if-statement (main.go:10:2); consider using short syntax (ifshort)
        name := "Jacob"
```

**Comment by esimonov** [comment]
Thanks for your interest!

@jacobbogdanov The first false positive you reported has already been fixed (https://github.com/esimonov/ifshort/commit/113a74d19ea0ee25cc342b28ca7c8895b7ce64b8) and released in version 1.0.1. Please stay tuned for golanci-lint 1.36.1.
The second one, together with the one reported by @AlekSi , is fixed in https://github.com/esimonov/ifshort/commit/0ee1452442442c8af1559a6bf75601313aa489c6.

**Comment by jpreese** [comment]
Just ran into the second case as well. Thanks for the fix! Hope to see it added to golanglinter soon 😄

**Comment by esimonov** [comment]
Sorry for not releasing it for so long. `v1.0.2` is out and merged into golanci-lint. Stay tuned for its new release.
